name = "skin-cancer-detection-workers"
main = "index.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2024-07-30"

kv_namespaces = [
    { binding = "FOO", id = "<YOUR_KV_NAMESPACE_ID>" }
]